export const COUNTRY_CODES: Record<string, string> = {
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AG: 'Antigua and Barbuda',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AR: 'Argentina',
  AT: 'Austria',
  AU: 'Australia',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BJ: 'Benin',
  BN: 'Brunei Darussalam',
  BO: 'Bolivia',
  BR: 'Brazil',
  BW: 'Botswana',
  BY: 'Belarus',
  BZ: 'Belize',
  CA: 'Canada',
  CD: 'Democratic Republic of the Congo',
  CF: 'Central African Republic',
  CH: 'Switzerland',
  CI: 'Ivory Coast',
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CU: 'Cuba',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DE: 'Germany',
  DJ: 'Djibouti',
  DK: 'Denmark',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  ER: 'Eritrea',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FR: 'France',
  GA: 'Gabon',
  GB: 'United Kingdom',
  GD: 'Grenada',
  GE: 'Georgia',
  GH: 'Ghana',
  GM: 'Gambia',
  GN: 'Guinea',
  GR: 'Greece',
  GY: 'Guyana',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IN: 'India',
  IQ: 'Iraq',
  IR: 'Iran',
  IS: 'Iceland',
  IT: 'Italy',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KM: 'Comoros',
  KN: 'Saint Kitts and Nevis',
  KR: 'South Korea',
  KW: 'Kuwait',
  KZ: 'Kazakhstan',
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LK: 'Sri Lanka',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  LY: 'Libya',
  MA: 'Morocco',
  MD: 'Moldova',
  MH: 'Marshall Islands',
  MK: 'North Macedonia',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MR: 'Mauritania',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MW: 'Malawi',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NE: 'Niger',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PT: 'Portugal',
  QA: 'Qatar',
  RU: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SB: 'Solomon Islands',
  SC: 'Seychelles',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SI: 'Slovenia',
  SK: 'Slovakia',
  SL: 'Sierra Leone',
  SN: 'Senegal',
  SO: 'Somalia',
  SY: 'Syria',
  SZ: 'Eswatini (Swaziland)',
  TD: 'Chad',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TR: 'Turkey',
  TT: 'Trinidad and Tobago',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UA: 'Ukraine',
  UG: 'Uganda',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VE: 'Venezuela',
  VN: 'Vietnam',
  YE: 'Yemen',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};

export const ZONES_BY_ID: Record<number, string> = {
  100: 'Four Seasons Hotel Abu Dhabi',
  1000: 'W Yas Island Hotel',
  1001: 'ALDAR ACADEMIES-WEST YAS SCHOOL L.L.C. -  BRANCH 6',
  1004: 'Yas Gateway Park South',
  1006: 'Centro Yas Island Hotel',
  1007: 'YAS',
  1017: 'ASPEN HEIGHTS BRITISH SCHOOL - Nursery',
  1018: 'Al Baheya Common School',
  1019: 'AL THURAYA KG',
  1020: 'SAAD BIN MOAATH',
  1022: 'حديقة فراشات',
  1024: 'Sweet Baby Nursery',
  1025: 'AL BASMA BRITISH SCHOOL - Nursery',
  1026: 'French Doll Nursery',
  1027: 'IQ Kids Nursery - Branch',
  1028: 'ABDUL QADER AL JAZAERI',
  1030: 'HALIMA AL SAADIAH',
  1034: 'Ibn Sina',
  1035: 'AL RAHBA HOSPITAL',
  1044: 'AL MOKTASHIF AL SAGHIR KG',
  1048: 'AL RAHBA',
  1050: 'AL EBTEHAL KG',
  1057: 'AL TAWEELAH',
  1060: 'AL SAMHA',
  1062: 'ASHABAL AL QUDS SECONDARY PRIVATE SCHOOL',
  1063: 'CAMBRIDGE MEDICAL & REHABILITATION CENTRE L.L.C BRANCH 1',
  1064: 'Little Rainbow Nursery',
  1065: 'Al Dana Branch 3',
  1067: 'NATIONAL REHABILITATION CENTRE',
  1069: 'Small Stars',
  1070: 'DISABLED CUSTODIAL CARE CENTER ( DCCC)',
  1071: 'VIRGINIA INTERNATIONAL PRIVATE SCHOOL',
  1074: 'A B C PRIVATE SCHOOL',
  1079: 'Al Riyadh Hotel Apartment',
  108: 'CLEVELAND CLINIC ABU DHABI LLC',
  1081: 'Al Riyadh',
  1083: 'Barney Home Branch 2',
  1089: 'AL QEMMA',
  1090: 'AL YASAT PRIVATE SCHOOL',
  1100: 'AL MANARA PRIVATE SCHOOL',
  1137: 'Al-Shamkha Plaza',
  1176: 'Applied Technology High School - Abu Dhabi  - Boys - Baniyas',
  1182: 'ALJAZIRA FOOTBALL ACADEMY',
  1197: 'AL FATEH',
  1198: 'AL ASALAH',
  1263: 'AL MAHA',
  1272: 'THE PHILIPPINE SCHOOL',
  1273: 'GLOBAL INDIAN INTERNATIONAL SCHOOL - LLC',
  1274: 'Baniyas Plaza Hotel Apartments',
  1275: 'BANI YAS CITY',
  1277: 'DAR AL ULOOM PRIVATE SCHOOL - BANIYAS',
  1280: 'UNITED PRIVATE SCHOOL -  BRANCH 1',
  1281: 'AL ZALLAQAH',
  1282: 'AL SOROOR KG',
  1283: 'Jern Yafoor',
  1285: 'AL BAWADI',
  1287: 'Baniyas Public Park',
  1288: 'Al Nahdha KG & C1',
  1289: 'Trampo Park',
  1290: 'AL MUNEERA PRIVATE SCHOOL  L.L.C.',
  1292: 'MAYOOR PRIVATE SCHOOL L.L.C.',
  1293: 'AL EZZAH',
  1296: 'AL LOULO',
  1298: 'OULA KG - ABU DHABI',
  1305: 'LIFECARE HOSPITAL L.L.C.',
  1306: 'AL WATHBA CENTER OF INTEGRATED CONTINUING EDUCATION (FEMALE - EVENING)',
  1307: 'AL MOZDALEFA',
  1310: 'Al Wathba Park',
  1316: 'Al Shariyah Ladies Garden',
  1323: 'Vocational Education Development Centre',
  1324: 'Aljazira Hotel & Resort',
  1336: 'ROOH AL ETIHAD',
  1339: 'OBADAH BIN AL SAMET',
  1342: 'Al-Khatam Park',
  1344: 'Al khatim safari',
  1351: 'إسترآحة احمد باصافي',
  1352: 'Sweihan Bird Training Complex',
  1357: 'Emirates National Auto Museum',
  1378: 'al Maya Island Resort',
  1402: 'AL SHOWAIB',
  1413: 'Al Bada  Resort',
  1419: 'Desert Rose Desert Camp',
  1430: 'Remah family Park',
  1434: 'AL MABADE',
  1436: 'Telal Resort',
  1444: 'AL KHAIR',
  1454: 'UM AL FADHEL BINT AL HARETH',
  1456: 'Capital Gate Camp',
  1460: 'alsalamat park',
  1461: 'AL SAWSAN KG',
  1492: 'AL DANAT',
  1498: 'AL SOMOU',
  1504: 'Al Dhaher',
  1506: 'Al Dhaher KG & C1',
  1508: 'Al Dhahir Park',
  1509: 'TIFEL AL EMARAT KG',
  1513: 'Barari Outlet Mall',
  1515: 'Park 2',
  1517: 'MEDICLINIC HOSPITALS L.L.C. ( AL JOWHARA HOSPITAL )',
  1518: 'Souq Al Zafarana',
  1519: 'Jack and Jill Nursery',
  1520: 'Barney Nursery',
  1523: 'AL AIN HOSPITAL',
  1524: 'AIN AL KHALEEJ HOSPITAL',
  1530: 'Abu Dhabi Police Nursery - Al Ain Branch',
  1533: 'Tolerance Schools - Al Mutarid',
  1535: 'CZECH REHABILITATION HOSPITAL   - SOLE PROPRIETORSHIP L.L.C.',
  1537: 'Ayla Hotel',
  1539: 'Al Masa Plus Hotel',
  1541: 'SULTAN BIN ZAYED',
  1561: 'AL SEDDIQUE  PRIVATE SCHOOL',
  1562: 'Al Ain Rotana Hotel',
  1565: 'Al Qattara Art Center',
  1571: 'Golden Bell',
  1573: 'KHALIFAH BIN ZAYED (AL AIN)',
  1577: 'Al Jahli Park',
  1578: 'AL JIMI KG',
  1579: 'BURJEEL ROYAL HOSPITAL L.L.C.',
  1580: 'AL JAHILI',
  1581: 'SPECIALIZED MEDICAL CARE HOSPITAL',
  1585: 'AL NAHYANIYYAH',
  1590: 'Emirates Commercial Complex',
  1591: 'Al Massa Hotel Apartments 1',
  1599: 'Al Ain Oasis',
  1602: 'KANAD HOSPITAL',
  1603: 'MEDICLINIC HOSPITALS L.L.C. ( AL AIN BRANCH HOSPITAL )',
  1604: 'Vegetable & Meat Market',
  1610: 'Kuwaitat Al Ain',
  1616: 'Trampo Extreme Al Ain',
  1618: 'ALDAR ACADEMIES-AL AIN INTERNATIONAL SCHOOL L.L.C. -  BRANCH 3',
  1624: 'Danat Alain Resort',
  1628: 'INTERNATIONAL SCHOOL OF CHOUEIFAT - BRANCH',
  1633: 'LAVENDER NURSERY',
  1634: 'Kids Land Nursery',
  1635: 'Al Basra Park',
  1640: 'Al Wadi Park',
  1641: 'OUR OWN ENGLISH HIGH SCHOOL',
  1642: 'MOHAMMED BIN KHALED',
  1644: 'AL FARAH MEDICAL REHABILTATION CENTER - SOLE PROPRIETORSHIP L.L.C',
  1647: 'City Seasons Hotel',
  1649: 'UNIVERSAL PRIVATE BRITISH CURRICULUM',
  1650: "AL ADHWA' PRIVATE SCHOOL",
  1654: 'GLOBAL ENGLISH SCHOOL',
  1658: 'AL TAMAYYOZ',
  1659: 'MOHAMMED BIN KHALID AL NAHYAN GENERATIONS SCHOOL  (MBK)',
  166: 'Worldwide Zoo Consultants',
  1663: 'AL MAALI',
  1664: 'Al Ain care and Rehabilitation School',
  1667: 'Al Towayya Park',
  1668: 'ABU DHABI ISLAND INTERNATIONAL PRIVATE SCHOOL',
  1669: 'Kids Nest',
  1671: 'MARYAM BINT SULTAN',
  1672: 'EMIRATES NATIONAL SCHOOL- BR.-Al Ain',
  1675: 'AMANA HEALTH CARE MEDICAL AND REHABILITATION HOSPITAL L.L.C -BRANCH 2',
  1679: 'Little Pearls',
  1682: 'AL TAFAWWUQ AL ILMI PRIVATE SCHOOL',
  1686: 'EMIRATES INTERNATIONAL HOSPITAL - SOLE PROPRIETORSHIP L.L.C.',
  1690: 'PINK AND BLUE NURSERY -BRANCH',
  1691: 'AMERICAN NATIONAL SCHOOL',
  1697: 'AL SADARAH',
  1699: 'Planets Montessori',
  1700: 'ABDULLA  BIN AL ZUBAIR PRIVATE SCHOOL',
  1701: 'AL GHAITH',
  1703: 'al maqam ladies parks',
  1704: 'UM KOLTHOOM',
  1705: 'AL MAQAM',
  171: 'Shams Boutik',
  1711: 'AL HEMMAH',
  1714: 'Little Regent Nursery',
  1715: 'TAWAM HOSPITAL',
  1720: 'AL AIN - AMERICAN PRIVATE SCHOOL',
  1726: 'BURJEEL FARHA HOSPITAL L.L.C.',
  1740: 'AL HAMDANIYA GRAND PRIVATE SCHOOL L.L.C.',
  1742: 'FUNSCAPES ENTERTAINMENT',
  1744: 'Little Hand',
  1747: 'AL SAAD INDIAN SCHOOL',
  1748: 'CAMBRIDGE MEDICAL & REHABILITATION CENTRE L.L.C.',
  1755: 'LONG TERM MEDICAL AND REHABILITATION HOSPITAL LLC',
  1756: 'Edu Fun Nursery - Branch',
  1758: 'AHMED BIN ZAYED',
  1759: 'Nahyan Al Awal KG',
  1763: 'HESSA BINT MOHAMMAD',
  1765: 'Top Kids',
  1767: 'Applied Technology High School – Al Ain – Girls – Al Aqabiya',
  1776: 'Sheikh Zayed Desert Learning Centre',
  1784: 'Shabhat Plaza',
  1786: 'INTERNATIONAL PRIVATE SCHOOL',
  1788: 'Remal Mall',
  1790: 'KHALED BIN AL WALEED',
  1795: 'Al Dana Branch 8',
  1799: 'Radisson Blu Hotel Abu Dhabi Alain',
  1806: 'Ayla Bawadi Hotel',
  1807: 'Applied Technology High School – Al Ain – Boys – Tahnoun bin Mohammed  Educational Complex',
  1819: 'REVITAL REHABILITATION HOSPITAL',
  1820: 'Hili Fun City',
  1821: 'AL TAFAWWOQ (AL AIN)',
  1826: 'N M C PROVITA INTERNATIONAL MEDICAL CENTER LTD - BRANCH 1',
  1827: 'Hili Archaeological park',
  1828: 'AL AIN MODEL',
  1829: 'HILI',
  1831: 'Letters and Numbers',
  1834: 'UM AL EMARAT (AL AIN)',
  1838: 'Hili Rayhaan By Rotana',
  1839: 'Safeer Mall',
  1840: 'Al Waha Mall',
  1844: 'Asfar Resorte',
  1845: 'Al Qattara Oasis',
  1855: 'Ain Al Fayedha',
  1856: 'Neima C3 Boys',
  1864: 'DALMA AL JADEEDAH P84',
  1867: 'Western Souq & Mall',
  1868: 'Al Dhafra Mall',
  1869: 'AL DHAFRA',
  1870: 'ASIAN INTERNATIONAL PRIVATE SCHOOL LLC',
  1873: 'Al Dhafra Walk',
  1878: 'Tilal Liwa Hotel',
  1894: 'Qasr Al Sarab Hotel',
  1902: 'Liwa Hotel',
  1914: 'KHANOOR',
  1916: 'AL MARFAA INTERNATIONAL',
  1922: 'مجمع ألعاب - 4',
  1934: 'BEDAA AL MUTAWA',
  1940: 'Ruwais City Farm-Mini Zoo',
  1941: 'Aqua Park Ghayathi',
  1946: 'Sir Bani Yas Wildlife Park',
  1950: 'DELMA HOSPITAL',
  1952: 'AL HOSN SCIENTIFIC SCHOOL',
  1959: 'DALMA',
  2035: 'PINNACLE AMERICAN SCHOOL',
  2036: 'MANAR AL ILM BRITISH CURRICULUM',
  2039: 'ZAYED AL KHAIR',
  2044: 'Applied Technology High School - Al Dhafra Region – Girls',
  2049: 'ADNOC SCHOOLS - MADINAT ZAYED -  BRANCH 1',
  2052: 'AL HUITEEN',
  2055: 'LIWA HOSPITAL',
  2068: 'AL SHOMOOKH',
  2069: 'AL NOKHBAH',
  2077: ' Mirfa Beach',
  2080: 'MARFA HOSPITAL',
  2081: 'مجمع ألعاب - 1',
  2099: 'Fun City',
  21: 'Bright Beginnings Nursery - Saadiyat',
  2100: 'Remal Hotel',
  2101: 'BAYAAT AL REDHWAN',
  2102: 'ADNOC SCHOOLS - GHAYATHI -  BRANCH 3',
  2107: 'L & ch. Garden',
  2108: 'Western Hotel Ghayathi',
  2109: 'AL EBTEKAR',
  2113: 'AL SHABHANA',
  2114: 'SILA HOSPITAL',
  2120: 'Liwa P42',
  2121: 'BAYAH',
  2135: 'محمية الأنعام',
  2142: "'Aliah Mall",
  215: 'Reem Mall',
  2152: 'UNITED PRIVATE SCHOOL',
  2153: 'Al Yahar North Park',
  2164: 'AL WAGAN HOSPITAL',
  2180: 'AL SARIYAH',
  2184: 'Nahel Park',
  2186: 'AL HAYAR',
  2188: 'Al Hayer oasis Park',
  2191: 'Al Nayfa KG',
  2192: 'UMM AL ARAB',
  2194: 'Al Rayana',
  2201: 'Al Falah Central Mall',
  2207: 'Sea World Abu Dhabi',
  2213: 'SABIS INTERNATIONAL SCHOOL - YAS ISLAND L.L.C.',
  2218: 'Yas Bay Hotel',
  2238: 'Andalus Alseef Resort And Spa',
  2240: 'GLOBAL MONTESSORI',
  2241: "The Montessori Children's Garden",
  2254: 'حدائق حارات العوامر الجديدة',
  2257: 'AL SAHAB KG',
  2268: 'GHIATHY HOSPITAL',
  2284: 'Madinat Zayed Lakes',
  2289: 'Al Selaa Care and Rehabilitation School',
  2290: 'AL SELAA',
  2299: 'ZOOMZO',
  2300: 'Marabia pocket garden-8',
  2301: 'AL SHATHA KG',
  2309: 'AL REYADA',
  2311: 'Dusit Thani Abu Dhabi H.A',
  2312: 'Little Garden Nursery',
  2315: 'ALDAR ACADEMIES-AL MAMOURA SCHOOL L.L.C. -  BRANCH 5',
  2316: 'Ministry of Culture and Knowledge Development',
  2318: 'Emirates British Nursery',
  2319: 'Ibis Gate Hotel',
  2321: 'Bright Kids Nursery - Branch 1',
  2324: 'The National Aquarium Abu Dhabi',
  2331: 'Magic Planet',
  2352: 'Yas Gateway Park North',
  2359: 'Emirates Park Zoo',
  2379: 'Yellow Submarine Nursery – Al Zeina',
  2383: 'YELLOW SUBMARINE - BRANCH 2 AL MUNEERA',
  2423: 'AL FORSAN',
  2424: 'Marriott Alforsan Hotel',
  2505: 'Green Mubazzarah Chalets',
  2511: 'Orange Seeds',
  2516: 'The Ritz',
  2521: 'BU KOREYYA',
  2552: 'AL DHAHERA',
  2565: 'AJYAL INTERNATIONAL SCHOOL NURSERY AL FALAH',
  2568: 'INTERNATIONAL COMMUNITY SCHOOLS - BR 22',
  2569: 'AL FALAH KG',
  2573: 'AL RESALAH',
  2592: 'Al hayer Lake Park',
  2631: 'Circuit X Splash Park',
  2632: 'Laguna Beach Abu Dhabi',
  2664: 'BRITISH OAK MONTESSORI',
  2709: 'Jubail Mangrove Park',
  2711: 'Al Wathba Resort',
  2717: 'Tolerance Schools - Al Khaznah',
  2725: 'Shangri - La Hotel Apartment',
  2726: 'Fairy Tale Nursery',
  2739: 'Al Marfa Hotel',
  275: 'Playhouse Nursery - Branch 1',
  2753: 'Al Slemi Park',
  277: 'Orca Park',
  2771: 'Reem Hospital L.L.C',
  2804: 'Small Stars - Branch 2',
  2819: 'AL MORJAN KG',
  2841: 'Aloft Al Ain Hotel',
  286: 'REPTON FOUNDATION SCHOOL L.L.C. - Nursery',
  288: 'Circuit X Adventure Park',
  2910: 'AL DAR PRIVATE SCHOOL',
  2915: 'Jabal Hafit Desert Park (Pura Hotel)',
  2921: 'Al Rayaheen School',
  2925: 'Alberni Jabal Hafeet Hotel',
  2926: 'Jabel Hafeet',
  2927: 'Mbazzarah Al Khadra',
  2963: 'MADINAT ZAYED HOSPITAL',
  2965: 'Flamingo viewing station',
  2985: 'Nurai Island Hotel',
  3024: 'Mini Zoo',
  3028: 'RAMAH',
  3031: 'CRANLEIGH SCHOOL ABU DHABI',
  3060: 'Park Hyatt Abu Dhabi Hotel And Villas',
  3063: 'Redwood Nursery Branch 2',
  307: 'Hummingbird Nursery',
  3073: 'St.Regis Saadiyat',
  3091: 'UM GHAFA',
  3094: 'BLOOM ACADEMY  L.L.C.',
  3096: 'TAHNOON BIN MOHAMMAD',
  3175: 'Alkhalidia Palace Rayhaan Hotel',
  3181: 'Abu Dhabi Wildlife Centre',
  3207: 'Yas Waterworld Abu Dhabi',
  3271: 'Rosewood Abu Dhabi Hotel',
  3285: 'MEDICLINIC HOSPITALS L.L.C. (AIRPORT ROAD HOSPITAL)',
  3301: 'My City Centre Masdar',
  3335: 'Al Dhafra Beach Hotel',
  3407: 'AlWathba Salt Lake (Sabkha)',
  3409: 'Al Nahdha KG',
  3447: 'ABU DHABI INDIAN SCHOOL -  BRANCH 1',
  345: 'Abu Dhabi Dates Market',
  357: 'Mina Center',
  372: 'Emirates Heritage Club Heritage Village',
  373: 'Greenopia Nursery',
  374: 'Bedayati Nursery - Branch 1',
  377: 'BEVERLY HILLS SPECIALIST HOSPITAL-SOLE PROPRIETORSHIP L.L.C',
  380: 'Umm Al Emarat Park',
  388: 'Jigsaw Nursery',
  391: 'Applied Technology High School - Abu Dhabi - Girls',
  392: 'AG Hotel',
  393: 'First Steps Nursery',
  394: 'Aldiar Sawa Hotel Apartments',
  396: 'Wanasa Land',
  399: 'THE BRITISH SCHOOL AL KHUBAIRAT - Nursery',
  40: 'Jumeirah At Saadiyat Island Resort',
  400: 'AL EMAN PRIVATE SCHOOL - LLC',
  403: 'Nehal Hotel',
  405: 'AL BATEEN SCIENTIFIC PRIVATE SCHOOL',
  406: 'Apple Bee Nursery',
  407: 'Al Jazira Club Hotel',
  408: 'ABU DHABI INTERNATIONAL PRIVATE SCHOOL W L L',
  409: 'British Orchard',
  410: 'ALDAR ACADEMIES-ALBATEEN SCHOOL L.L.C. -  BRANCH 4',
  413: 'LIWA INTERNATIONAL SCHOOL- AL MUSHRIF',
  417: 'NMC ROYAL WOMENS HOSPITAL LTD',
  419: 'SEHA EMIRATES HOSPITAL L.L.C',
  422: 'EMIRATES NATIONAL SCHOOL -  BRANCH 3 -Manaser',
  427: 'Bright Kids Nursery - Branch 3',
  430: 'Bright Beginnings Nursery - Mehairba',
  432: 'Bait Al Oud',
  453: 'Royal Palace Nursery',
  456: 'INTERNATIONAL COMMUNITY SCHOOL - L L C',
  458: 'Al Dana Branch 4',
  459: 'HAMDAN BIN ZAYED C2 AND 3 BOY',
  46: 'CRANLEIGH SCHOOL ABU DHABI - Nursery',
  461: 'SHEIKH KHALIFA BIN ZAYED ARAB PAKISTAN SCHOOL- LLC',
  462: 'Al Mushrif KG',
  463: 'Al Khaleej Al Arabi Park-Picnic-2',
  466: 'VISION PRIVATE SCHOOL  LLC',
  467: 'AISHAH BINT ABI BAKER',
  480: 'KHALIFAH BIN ZAYED',
  481: "Sparky's",
  482: 'PLUS INTERNATIONAL MEDICAL CENTRE LLC',
  483: 'Les Fanfans Nursery',
  484: 'Loulou Asfar Hotel Apartments',
  486: 'Dolphin Park (Eastern Mangroves Park)',
  487: 'AL MANHAL INTERNATIONAL PRIVATE SCHOOL',
  489: 'Al Bateen Ladies Beach',
  492: 'Bright Kids Nursery',
  494: 'ABU DHABI INDIAN SCHOOL',
  495: 'ZAYED MILITARY HOSPITAL',
  498: 'Adagio Serviced Apartment Al Bustan',
  501: 'Lycée Louis Massignon',
  502: 'Novotel Hotel Al Bustan',
  503: 'Capital Centre Arjaan By Rotana',
  507: 'Al Qurm Beach',
  508: 'SHAIKH KHALIFA BIN ZAYED BANGLADESH ISLAMIA PRIVATE SCHOOL - LLC',
  509: 'AL REEM',
  51: 'Manarat Al Sadiyaat',
  512: 'Bright Beginnings Nursery - Mushrif',
  515: 'Rosewood Nursery',
  517: 'EMIRATES PRIVATE SCHOOL',
  523: 'Anantara Eastern Mangroves Hotel',
  524: 'Abu Dhabi History Museum and Aquarium',
  525: 'BLOOM GARDENS SCHOOL L.L.C L.L.C. - Nursery',
  527: 'Holiday Inn Abu Dhabi',
  529: 'Educare Private L.L.C',
  531: " CHILDREN'S OASIS MINISTRY OF INTERIOR",
  533: 'Health point Hospital LLC',
  534: 'Al Khaleej Al Arabi Park-Picnic5',
  535: 'New Visitor Center & Plaza at Sheikh Zayed Grand Mosque Extension',
  537: 'Armed Forces Officer Club Hotel',
  538: 'NOVOMED PLASTIC SURGERY HOSPITAL L.L.C',
  542: 'SPECIALIZED REHABILITATION HOSPITAL L.L.C',
  544: 'Prison Island Abu Dhabi',
  546: 'Splash Park',
  552: 'Playhouse Nursery',
  557: 'Courtyard By Marriott Wtc',
  559: 'KIDS FANTASY NURSERY',
  561: 'Cultural Foundation',
  564: 'Discus.ae',
  566: 'Al Muhairy Centre',
  567: 'The mall',
  570: 'Rotana Mall',
  571: 'Fotouh AlKhair Mall',
  573: 'Sparkys Amusement Center',
  576: 'Oryx Hotel',
  577: 'INTERNATIONAL COMMUNITY SCHOOL - BR4',
  580: 'MEDICLINIC HOSPITALS L.L.C. (AL NOOR HOSPITAL)',
  581: 'Khalidiya Public Park',
  583: 'Uptown Hotel Apartment',
  584: 'LLH HOSPITAL L.L.C',
  586: 'Lake Park',
  588: 'AL AHLI  HOSPITAL COMPANY - WLL',
  589: 'Down Town Plaza H.A',
  59: 'Berklee Abu Dhabi',
  602: 'Al Jazeera Royal Hotel',
  604: 'GERMAN INTERNATIONAL SCHOOL',
  605: 'Al Butin Nursery',
  610: 'Capital Park',
  611: 'Rainbow Hotel Apartments',
  614: 'Lady Bird Nursery',
  616: 'FUTURE LEADERS INTERNATIONAL PRIVATE SCHOOL - Branch2',
  617: 'SHEIKH KHALIFA MEDICAL CITY',
  620: 'Trianon  Royal Hotel',
  621: 'Abu Dhabi Plaza H.A',
  622: 'Le Royal Meridien Abu Dhabi',
  624: 'Radisson Blu Hotel',
  625: 'Step by Step Nursery - Abu Dhabi Branch',
  626: 'Marriott Executive Apartments Downtown',
  629: 'JAPANESE SCHOOL',
  630: 'Al Maha Arjaan H.A',
  632: 'Bright Kids Nursery - Branch 2',
  633: 'Al Nakheel Hotel Apartments',
  635: 'Formal Park',
  637: 'Mubarak Bin Mohammed',
  639: 'Golden Tulip Downtown Hotel',
  641: 'Nation Towers Mall',
  642: 'AL GHAZALI',
  643: 'St.Regis Abudhabi Hotel',
  644: 'MEDEOR 24X7 HOSPITAL - L.L.C.',
  646: 'Queen Palace Hotel',
  648: 'Sofitel Abu Dhabi Corniche',
  651: 'Leens Nursery',
  659: 'Royal Rose Hotel',
  662: 'Tolerance Schools - Al Danah',
  664: 'Grand Millennium Al Wahda Hotel',
  665: 'Vision Nursery - Branch 1',
  667: 'Bainunah Park',
  668: 'Redwood Nursery Branch 1',
  669: 'KIDS FANTASY NURSERY BRANCH 3',
  675: 'KIDS FANTASY NURSERY -BRANCH 1',
  676: 'GEMS WORLD ACADEMY  L.L.C.',
  679: 'BURJEEL HOSPITAL LLC',
  680: 'THE SPANISH SCHOOL OF ABU DHABI',
  682: 'Edition Hotel Llc',
  684: 'Emirates Palace Hotel',
  685: 'CORNICHE HOSPITAL.',
  688: 'Intercontinental Hotel Abu Dhabi',
  689: 'YAS ACADEMY SCHOOL',
  690: 'POLARIS PRIVATE ACADEMY L.L.C.',
  691: 'Kings Gate Hotel',
  692: 'Emirate Plaza Hotel',
  693: 'Ivory Hotel Apartment.',
  695: 'Observation Deck at 300',
  696: 'Strand Hotel',
  699: 'Spring Fields Nursery',
  701: 'Almanzel Hotel Apartments',
  709: 'Liwa Executive Suites',
  710: 'Le Meridien Hotel Abu Dhabi',
  711: 'Heritage Garden',
  713: 'Ramada Hotel',
  714: 'MINISTRY OF PRESIDENTIAL AFFAIRS',
  721: 'ADNOC SCHOOLS - SAS AL NAKHL',
  723: 'DANAT AL EMARAT HOSPITAL FOR WOMEN & CHILDREN L.L.C',
  724: 'Rabdan C2 Boys',
  727: 'Fairmont Bab Al Bahr Hotel',
  730: 'The Westin Abu Dhabi',
  734: 'DIYAFAH INTERNATIONAL SCHOOL L.L.C.',
  736: 'BAREEN INTERNATIONAL HOSPITAL',
  740: 'Vision Nursery',
  741: 'Liverpool Nursery - Branch 1',
  743: 'Kids Island Nursery',
  744: 'Al Budoor KG',
  745: 'LITTLE HELPERS',
  748: 'ABU DHABI INTERNATIONAL SCHOOL-MBZ',
  749: 'NEW ENGLAND CENTRE FOR CHILDREN',
  750: 'BURJEEL MEDICAL CITY L.L.C.',
  753: 'Rainbow Nursery',
  756: 'Gravity Hotel',
  757: 'EMIRATES FUTURE INTERNATIONAL ACADEMY PRIVATE SCHOOL',
  759: 'PHOENIX HOSPITAL L.L.C.',
  763: 'Sponge Bob',
  766: 'AL BASHAIR PRIVATE SCHOOL',
  768: 'Dazzling Stars Nursery',
  770: 'Al Ghad',
  771: 'Mazyad Mall',
  773: 'Le Arabia Hotel Apartment',
  778: 'Al Danah',
  782: 'Action Zone - Capital Mall',
  805: 'ICAD MALLl',
  819: 'Fun City - Dalma Mall',
  845: 'MILLENNIUM HOSPITAL L.L.C',
  847: 'The Village Mall',
  858: 'LLH HOSPITAL AL MUSAFFAH L.L.C',
  864: 'Hotel And Chalets Of Al Raha Beach',
  871: 'RAHA INTERNATIONAL SCHOOL',
  875: 'ALDAR ACADEMIES-AL YASMINA SCHOOL L.L.C. - Nursery',
  890: 'SAS AL NAKHL',
  891: 'N M C ROYAL HOSPITAL LTD',
  894: 'Splash Pad',
  897: 'Super Nany Nursery',
  903: 'Kids Academy',
  905: 'AL RUDWAN KG',
  908: 'TEDDY BEAR NURSERY - SOLE PROPRIETORSHIP L.L.C.',
  909: 'N M C PROVITA INTERNATIONAL MEDICAL CENTER LTD- ABU DHABI',
  910: 'Windsor Early Years Nursery',
  915: 'Deerfields nursery',
  917: 'Redwood Nursery',
  92: 'Eastern Mangrove National Park',
  920: 'Disney Nursery',
  921: 'RAHA INTERNATIONAL SCHOOL - KHALIFA A',
  922: 'AL SHOHUB PRIVATE SCHOOL - LLC',
  923: 'Starfish Lane Nursery',
  924: 'Saray Hotel Apartments',
  926: 'Learning Spaces Nursery',
  929: 'Treehouse Nursery',
  932: 'Yas Clinic Khalifa City  Sole Proprietorship L.L.C',
  935: 'Al DHAFRA – HOME STUDY',
  936: 'ICHIBAN',
  942: 'First Hope Nursery',
  944: 'INTERNATIONAL COMMUNITY SCHOOL - L L C -  BRANCH 3',
  978: 'BLOSSOM - BRANCH OF ABU DHABI 1',
  983: 'Premier Inn Hotels',
  987: 'AL REEF CENTER OF INTEGRATED CONTINUING EDUCATION-APPLIED STREAM (Mixed- EVENING)',
  988: 'RYAN INTERNATIONAL SCHOOL LIMITED',
  99: 'National Geographic Ultimate Explorer AD',
  990: 'New Airport Garden',
  991: 'Maple Tree International LLC',
  992: 'Warner Bros World Abu Dhabi',
  993: 'DARE',
  994: 'KidZania - Abu Dhabi',
  996: 'Double Tree By Hilton Residences',
};
