import { Slide } from '../dashboard/types.ts';
import { LocationType } from '../locationPanel/types.ts';
import { ChartConfig } from './types.ts';

export const CHARTS_CONFIG: Partial<Record<Slide, ChartConfig>> = {
  [Slide.PEOPLE_BEHAVIOR_OVERVIEW]: [],

  [Slide.POPULATION_COUNT]: [
    {
      url: 'peoplecount/charts/gender',
      params: ['location', 'locationType', 'year'],
      id: 'gender',
      name: 'Gender',
      type: 'pie',
    },
    {
      url: 'peoplecount/charts/nationality',
      params: ['location', 'locationType', 'year'],
      id: 'nationality',
      name: 'Nationality',
      type: 'pie',
    },
    {
      url: 'peoplecount/charts/age',
      params: ['location', 'locationType', 'year'],
      id: 'age',
      name: 'Age',
      type: 'pie',
    },
    {
      url: 'peoplecount/charts/income',
      params: ['location', 'locationType', 'horizonInPast'],
      id: 'income',
      name: 'Income',
      type: 'pie',
    },
    {
      url: 'peoplecount/charts/occupation',
      params: ['location', 'locationType', 'horizonInPast'],
      id: 'occupation',
      name: 'Occupation',
      type: 'bar',
    },
    {
      url: 'peoplecount/charts/cars',
      params: ['location', 'locationType'],
      id: 'cars',
      name: 'Car Ownership',
      type: 'value',
      label: 'Cars/1000 Persons',
    },
  ],

  [Slide.POPULATION_MOVEMENT_INBOUND]: [
    {
      url: 'peoplemovementinbound/charts/modesoftransport',
      params: ['location', 'locationType', 'horizon'],
      id: 'modesoftransport',
      name: 'Modes of Transport',
      type: 'pie',
    },
    {
      url: 'peoplemovementinbound/toporigins',
      params: ['location', 'locationType', 'quarter'],
      id: 'toporigins',
      name: 'Top Origins',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Trips / Day',
    },
  ],

  [Slide.POPULATION_MOVEMENT_OUTBOUND]: [
    {
      url: 'peoplemovementoutbound/charts/modesoftransport',
      params: ['location', 'locationType', 'horizon'],
      id: 'modesoftransport',
      name: 'Modes of Transport',
      type: 'pie',
    },
    {
      url: 'peoplemovementoutbound/topdestinations',
      params: ['location', 'locationType', 'quarter'],
      id: 'topdestinations',
      name: 'Top Destinations',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Trips / Day',
    },
  ],

  [Slide.POPULATION_MOVEMENT_WITHIN]: [
    {
      url: 'peoplemovementwithin/charts/modesoftransport',
      params: ['location', 'locationType', 'horizon'],
      id: 'modesoftransport',
      name: 'Modes of Transport',
      type: 'pie',
    },
    {
      url: 'peoplemovementwithin/charts/top',
      params: ['location', 'locationType', 'quarter'],
      id: 'top',
      name: 'Top Destinations',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Trips / Day',
    },
  ],

  [Slide.LAND_USE_OVERVIEW]: [
    {
      url: ['landuseoverview/percentofbuilt', 'landuseoverview/utilization', 'landuseoverview/occupancyRate'],
      urlLabelsMapping: ['% of Built', 'Utilisation', 'Occupancy'],
      params: [
        ['location', 'locationType', 'horizon'],
        ['location', 'locationType', 'quarter'],
        ['location', 'locationType', 'quarter'],
      ],
      id: 'generalstatus',
      name: 'General Status',
      type: 'bar',
      maxValue: 100,
      unit: '%',
    },
    {
      url: 'landuseoverview/classification',
      params: ['location', 'locationType', 'horizon'],
      id: 'classification',
      name: 'Classification',
      type: 'bar',
      columnSize: 5,
    },
  ],

  [Slide.SUMMARY]: [],

  [Slide.LAND_USE_RESIDENTIAL]: [
    {
      url: 'residential/charts/occupancydetails',
      params: ['location', 'locationType', 'quarter'],
      id: 'occupancydetails',
      name: 'Occupancy Details',
      type: 'value',
    },
  ],

  [Slide.LAND_USE_RETAIL]: [],

  [Slide.LAND_USE_OFFICES]: [
    {
      url: 'offices/charts/workers',
      params: ['location', 'locationType', 'horizon'],
      id: 'workers',
      name: 'No. of Workers',
      type: 'value',
    },
    {
      url: 'offices/charts/officeJobsAvailable',
      params: ['location', 'locationType', 'horizon'],
      id: 'officeJobsAvailable',
      name: 'No. of Available Offices',
      type: 'value',
      label: '',
    },
  ],

  [Slide.LAND_USE_EDUCATION]: [
    {
      url: 'schools/charts/numberofestablishments',
      params: ['location', 'locationType'],
      id: 'numberOfEstablishments',
      name: 'No. of Establishments',
      type: 'pie',
    },
    {
      url: 'schools/charts/numberofstudents',
      params: ['location', 'locationType', 'rangeOfLastYearBeforeHorizon'],
      id: 'numberOfStudents',
      name: 'No. of Students',
      type: 'value',
    },
    {
      url: 'schools/charts/numberofstaff',
      params: ['location', 'locationType'],
      id: 'numberOfStaff',
      name: 'No. of Staff',
      type: 'pie',
    },
  ],

  [Slide.LAND_USE_INDUSTRY]: [],

  [Slide.LAND_USE_MEDICAL]: [],

  [Slide.LAND_USE_HOSPITALITY]: [],

  [Slide.LAND_USE_OTHERS]: [],

  [Slide.LAND_USE_WATER_CONSUMPTION]: [
    {
      url: 'waterconsumption/charts/top/residential/bylocation',
      params: ['location', 'locationType', 'quarter'],
      id: 'top/residential/bylocation',
      name: 'Top Residential Consumption (Location)',
      type: 'bar',
    },
    {
      url: 'waterconsumption/charts/top/residential/bypremise',
      params: ['location', 'locationType', 'quarter'],
      id: 'top/residential/bypremise',
      name: 'Top Residential Consumption (Premise)',
      type: 'bar',
    },
    {
      url: 'waterconsumption/charts/top/commercial/bylocation',
      params: ['location', 'locationType', 'quarter'],
      id: 'top/commercial/bylocation',
      name: 'Top Commercial Consumption (Location)',
      type: 'bar',
    },
    {
      url: 'waterconsumption/charts/top/commercial/bypremise',
      params: ['location', 'locationType', 'quarter'],
      id: 'top/commercial/bypremise',
      name: 'Top Commercial Consumption (Premise)',
      type: 'bar',
    },
    {
      url: 'waterconsumption/charts/overallConsumption',
      params: ['location', 'locationType', 'quarter'],
      id: 'overallConsumption',
      name: 'Overall Consumption',
      type: 'table',
      valueLabel: '',
      keyLabel: '',
    },
  ],

  [Slide.LAND_USE_ELECTRICITY_CONSUMPTION]: [
    {
      url: 'electricityconsumption/charts/top/residential/bylocation',
      params: ['location', 'locationType', 'quarter'],
      id: 'top/residential/bylocation',
      name: 'Top Residential Consumption (Location)',
      type: 'bar',
    },
    {
      url: 'electricityconsumption/charts/top/commercial/bylocation',
      params: ['location', 'locationType', 'quarter'],
      id: 'top/commercial/bylocation',
      name: 'Top Commercial Consumption (Location)',
      type: 'bar',
    },
    {
      url: 'electricityconsumption/charts/overallConsumption',
      params: ['location', 'locationType', 'quarter'],
      id: 'overallConsumption',
      name: 'Overall Consumption',
      type: 'table',
      valueLabel: '',
      keyLabel: '',
    },
  ],

  [Slide.LAND_USE_PLANNED_OFFICIAL]: [],

  [Slide.LAND_USE_PLANNED_DEVELOPER]: [],

  [Slide.MOBILITY_OVERVIEW]: [
    {
      url: 'mobility/overview/modeShare',
      params: ['location', 'locationType', 'horizon'],
      id: 'modeShare',
      name: 'Mode Share',
      type: 'pie',
    },
  ],

  [Slide.MOBILITY_TRIPS_INBOUND]: [
    {
      url: 'tripsinbound/charts/modeShare',
      params: ['location', 'locationType', 'horizon'],
      id: 'modeShare',
      name: 'Mode Share',
      type: 'pie',
    },
    {
      url: 'tripsinbound/charts/purpose',
      params: ['location', 'locationType', 'horizon'],
      id: 'tripinboundpurpose',
      name: 'Trip Purpose',
      type: 'pie',
    },
    {
      url: 'tripsinbound/charts/vehiclekmtraveled',
      params: ['location', 'locationType', 'horizon'],
      id: 'vehiclekmtraveled',
      name: 'Vehicle KM Traveled',
      type: 'value',
      label: 'Km/Day',
      valueDecimals: 0,
    },
  ],

  [Slide.MOBILITY_TRIPS_OUTBOUND]: [
    {
      url: 'tripsoutbound/charts/modeShare',
      params: ['location', 'locationType', 'horizon'],
      id: 'modeShare',
      name: 'Mode Share',
      type: 'pie',
    },
    {
      url: 'tripsoutbound/charts/purpose',
      params: ['location', 'locationType', 'horizon'],
      id: 'tripoutboundpurpose',
      name: 'Trip Purpose',
      type: 'pie',
    },
    {
      url: 'tripsoutbound/charts/vehiclekmtraveled',
      params: ['location', 'locationType', 'horizon'],
      id: 'vehiclekmtraveled',
      name: 'Vehicle KM Traveled',
      type: 'value',
      label: 'Km/Day',
      valueDecimals: 0,
    },
  ],

  [Slide.BUS_TRIPS_INBOUND]: [
    {
      url: 'bustripsinbound/charts/toporiginsbylocations',
      params: ['location', 'locationType', 'quarter'],
      id: 'toporiginsbylocations',
      name: 'Top 5 Origins - Locations',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Trips/Day',
    },
    {
      url: 'bustripsinbound/charts/toporiginsbybusstops',
      params: ['location', 'locationType', 'quarter'],
      id: 'toporiginsbybusstops',
      name: 'Top 5 Origins (Bus Stops)',
      type: 'table',
      keyLabel: 'Bus Stop Name',
      valueLabel: 'Trips/Day',
    },
    {
      url: 'bustripsinbound/charts/toptransfers',
      params: ['location', 'locationType', 'quarter'],
      id: 'toptransfers',
      name: 'Top 5 transfers (Bus Stops)',
      type: 'table',
      keyLabel: 'Bus Stop Name',
      valueLabel: 'Trips/Day',
    },
  ],

  [Slide.BUS_TRIPS_OUTBOUND]: [
    {
      url: 'bustripsoutbound/charts/topdestinationsbylocations',
      params: ['location', 'locationType', 'quarter'],
      id: 'top5destinationslocations',
      name: 'Top 5 Destinations (Locations)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Trips/Day',
    },
    {
      url: 'bustripsoutbound/charts/topdestinationsbybusstops',
      params: ['location', 'locationType', 'quarter'],
      id: 'topdestinationsbybusstops',
      name: 'Top 5 Destinations (Bus Stops)',
      type: 'table',
      keyLabel: 'Bus Stop Name',
      valueLabel: 'Trips/Day',
    },
    {
      url: 'bustripsoutbound/charts/toptransfers',
      params: ['location', 'locationType', 'quarter'],
      id: 'toptransfers',
      name: 'Top 5 Transfers (Bus Stops)',
      type: 'table',
      keyLabel: 'Bus Stop Name',
      valueLabel: 'Trips/Day',
    },
  ],

  [Slide.BUS_TRIPS_WITHIN]: [
    {
      url: 'bustripswithin/charts/toporiginsbylocations',
      params: ['location', 'locationType', 'quarter'],
      id: 'topOriginsRidership',
      name: 'Top Origins (Locations)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Trips/Day',
    },
    {
      url: 'bustripswithin/charts/topdestinationsbylocations',
      params: ['location', 'locationType', 'quarter'],
      id: 'topDestinationsRidership',
      name: 'Top Destinations (Locations)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Trips/Day',
    },
    {
      url: 'bustripswithin/charts/topdestinationsbybusstops',
      params: ['location', 'locationType', 'quarter'],
      id: 'topdestinationsbybusstops',
      name: 'Top 5 Destinations (Bus Stops)',
      type: 'table',
      keyLabel: 'Bus Stop Name',
      valueLabel: 'Trips/Day',
    },
    {
      url: 'bustripswithin/charts/toporiginsbybusstops',
      params: ['location', 'locationType', 'quarter'],
      id: 'toporiginsbybusstops',
      name: 'Top 5 Origins (Bus Stops)',
      type: 'table',
      keyLabel: 'Bus Stop Name',
      valueLabel: 'Trips/Day',
    },
    {
      url: 'bustripswithin/charts/toptransfers',
      params: ['location', 'locationType', 'quarter'],
      id: 'toptransfers',
      name: 'Top 5 Transfers (Bus Stops)',
      type: 'table',
      keyLabel: 'Bus Stop Name',
      valueLabel: 'Trips/Day',
    },
  ],

  [Slide.BUS_LINE_UTILIZATION]: [
    {
      url: 'BusLineUtilization/charts/numberoflines',
      params: ['location', 'locationType', 'quarter'],
      id: 'numberOfLines',
      name: 'No. of Lines (Maximum)',
      type: 'value',
    },
    {
      url: 'BusLineUtilization/charts/toplines',
      params: ['location', 'locationType', 'quarter'],
      id: 'topLinesRidership',
      name: 'Top Lines (Based on Ridership)',
      type: 'table',
      keyLabel: 'Line Name',
      valueLabel: 'Average Trips/Day',
    },
    {
      url: 'BusLineUtilization/charts/averageutilization',
      params: ['location', 'locationType', 'quarter'],
      id: 'averageutilization',
      name: 'Average Utilisation (%)',
      type: 'percent',
    },
    {
      url: 'BusLineUtilization/charts/topcongestedbusstops',
      params: ['location', 'locationType', 'quarter'],
      id: 'topcongestedbusstops',
      name: 'Top Congested Bus Stops',
      type: 'table',
      keyLabel: 'Bus Stop Name',
      valueLabel: 'Avg. No of Trips',
    },
    {
      url: 'BusLineUtilization/charts/modeshare',
      params: ['location', 'locationType', 'horizon'],
      id: 'modeshare',
      name: 'Bus Mode Share',
      type: 'pie',
    },
    {
      url: 'busLineUtilization/charts/topcongestedlines',
      params: ['location', 'locationType', 'quarter'],
      id: 'topcongestedlines',
      name: 'Top Congested Lines',
      type: 'table',
      keyLabel: 'Line Name',
      valueLabel: 'Avg. No of Trips',
    },
  ],

  [Slide.TAXI_TRIPS_INBOUND]: [
    {
      url: 'taxitripsinbound/charts/numberofuniquetaxi',
      params: ['location', 'locationType', 'quarter'],
      id: 'uniqueTaxi',
      name: 'Unique Taxi',
      type: 'value',
    },
    {
      url: 'TaxiTripsInbound/charts/taximodeshare',
      params: ['location', 'locationType', 'horizon'],
      id: 'taxiModeShare',
      name: 'Taxi Mode Share',
      type: 'pie',
    },
    {
      url: 'TaxiTripsInbound/charts/typeoftaxisonridership',
      params: ['location', 'locationType', 'quarter'],
      id: 'taxisOnRidership',
      name: 'Type of Taxis (Based on Ridership)',
      type: 'pie',
    },
    {
      url: 'taxitripsinbound/charts/shareoftotaldemand',
      params: ['location', 'locationType', 'quarter'],
      id: 'shareOfTotalDemand',
      name: 'Share of Total Demand',
      type: 'ring',
    },
    {
      url: 'taxitripsinbound/charts/toplandmarkspickups',
      params: ['location', 'locationType', 'quarter'],
      id: 'topLandmarksPickups',
      name: 'Top Landmarks (Pickups)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Total Pickups/Day',
    },
    {
      url: 'taxitripsinbound/charts/toplandmarksdropoff',
      params: ['location', 'locationType', 'quarter'],
      id: 'topLandmarksDropoff',
      name: 'Top Landmarks (Dropoffs)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Total Dropoffs/Day',
    },
  ],

  [Slide.TAXI_TRIPS_OUTBOUND]: [
    {
      url: 'taxitripsoutbound/charts/numberofuniquetaxi',
      params: ['location', 'locationType', 'quarter'],
      id: 'uniqueTaxi',
      name: 'Unique Taxi',
      type: 'value',
    },
    {
      url: 'TaxiTripsOutbound/charts/taximodeshare',
      params: ['location', 'locationType', 'horizon'],
      id: 'taxiModeShare',
      name: 'Taxi Mode Share',
      type: 'pie',
    },
    {
      url: 'TaxiTripsOutbound/charts/typeoftaxisonridership',
      params: ['location', 'locationType', 'quarter'],
      id: 'taxisOnRidership',
      name: 'Type of Taxis (Based on Ridership)',
      type: 'pie',
    },
    {
      url: 'taxitripsoutbound/charts/shareoftotaldemand',
      params: ['location', 'locationType', 'quarter'],
      id: 'shareOfTotalDemand',
      name: 'Share of Total Demand',
      type: 'ring',
    },
    {
      url: 'taxitripsoutbound/charts/toplandmarkspickups',
      params: ['location', 'locationType', 'quarter'],
      id: 'topLandmarksPickups',
      name: 'Top Landmarks (Pickups)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Total Pickups/Day',
    },
    {
      url: 'taxitripsoutbound/charts/toplandmarksdropoff',
      params: ['location', 'locationType', 'quarter'],
      id: 'topLandmarksDropoff',
      name: 'Top Landmarks (Dropoffs)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Total Dropoffs/Day',
    },
  ],

  [Slide.TAXI_TRIPS_WITHIN]: [
    {
      url: 'taxitripswithin/charts/shareoftotaldemand',
      params: ['location', 'locationType', 'quarter'],
      id: 'shareOfTotalDemand',
      name: 'Share of Total Demand',
      type: 'ring',
    },
    {
      url: 'TaxiTripsWithin/charts/taximodeshare',
      params: ['location', 'locationType', 'horizon'],
      id: 'taxiModeShare',
      name: 'Taxi Mode Share',
      type: 'pie',
    },
    {
      url: 'TaxiTripsWithin/charts/typeoftaxisonridership',
      params: ['location', 'locationType', 'quarter'],
      id: 'taxisOnRidership',
      name: 'Type of Taxis (Based on Ridership)',
      type: 'pie',
    },
    {
      url: 'taxitripswithin/charts/numberofuniquetaxi',
      params: ['location', 'locationType', 'quarter'],
      id: 'uniqueTaxi',
      name: 'Unique Taxi',
      type: 'value',
    },
    {
      url: 'taxitripswithin/charts/toplandmarkspickups',
      params: ['location', 'locationType', 'quarter'],
      id: 'topLandmarksPickups',
      name: 'Top Landmarks (Pickups)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Pickups/Day',
    },
    {
      url: 'taxitripswithin/charts/toplandmarksdropoff',
      params: ['location', 'locationType', 'quarter'],
      id: 'topLandmarksDropoff',
      name: 'Top Landmarks (Dropoffs)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Dropoffs/Day',
    },
  ],

  [Slide.STUDENTS_COUNT]: [
    {
      url: 'studentcount/charts/studentplaces',
      params: ['location', 'locationType', 'horizonInPast'],
      id: 'numberOfStudentPlaces',
      name: 'No. of Student Places',
      type: 'value',
      label: '',
    },
    {
      url: 'studentcount/charts/gender',
      params: ['location', 'locationType', 'quarter'],
      id: 'gender',
      name: 'Gender',
      type: 'pie',
    },
    {
      url: 'studentcount/charts/nationality',
      params: ['location', 'locationType', 'quarter'],
      id: 'nationality',
      name: 'Nationality',
      type: 'pie',
    },
    {
      url: 'studentcount/charts/educationalStage',
      params: ['location', 'locationType', 'quarter'],
      id: 'educationalstage',
      name: 'Educational Stage',
      type: 'pie',
    },
  ],

  [Slide.STUDENTS_TRIPS_INBOUND]: [
    {
      url: 'studenttripsinbound/charts/toporigins',
      params: ['location', 'locationType'],
      id: 'toporigins',
      name: 'Top Origins (Student Homes)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Type / Name',
    },
    {
      url: 'studenttripsinbound/charts/tripdistribution',
      params: ['location', 'locationType', 'quarter'],
      id: 'tripdistribution',
      name: 'Trip Distribution (Travel Time)',
      type: 'value',
    },
    {
      url: 'studenttripsinbound/charts/topschools',
      params: ['location', 'locationType'],
      id: 'topschools',
      name: 'Top Schools (Dest.)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Type / Name',
    },
    {
      url: 'studenttripsinbound/charts/modesoftransport',
      params: ['location', 'locationType', 'quarter'],
      id: 'modesoftransport',
      name: 'Modes of Transport',
      type: 'pie',
    },
  ],

  [Slide.STUDENTS_TRIPS_OUTBOUND]: [
    {
      url: 'studenttripsoutbound/charts/topdestinations',
      params: ['location', 'locationType'],
      id: 'topdestinations',
      name: 'Top Destinations (Schools)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Type / Name',
    },
    {
      url: 'studenttripsoutbound/charts/tripdistribution',
      params: ['location', 'locationType', 'quarter'],
      id: 'tripdistribution',
      name: 'Trip Distribution (Travel Time)',
      type: 'value',
    },
    {
      url: 'studenttripsoutbound/charts/topschools',
      params: ['location', 'locationType'],
      id: 'topschools',
      name: 'Top Schools (Dest.)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Type / Name',
    },
    {
      url: 'studenttripsoutbound/charts/modesoftransport',
      params: ['location', 'locationType', 'quarter'],
      id: 'modesoftransport',
      name: 'Modes of Transport',
      type: 'pie',
    },
  ],

  [Slide.STUDENTS_TRIPS_WITHIN]: [
    {
      url: 'studenttripswithin/charts/topdestinations',
      params: ['location', 'locationType'],
      id: 'topschools',
      name: 'Top Distinations (Schools)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Type / Name',
    },
    {
      url: 'studenttripswithin/charts/tripdistribution',
      params: ['location', 'locationType', 'quarter'],
      id: 'tripdistribution',
      name: 'Trip Distribution (Travel Time)',
      type: 'value',
    },
    {
      url: 'studenttripswithin/charts/topschools',
      params: ['location', 'locationType'],
      id: 'topschools',
      name: 'Top Schools (Dest.)',
      type: 'table',
      keyLabel: 'Location',
      valueLabel: 'Type / Name',
    },
    {
      url: 'studenttripswithin/charts/modesoftransport',
      params: ['location', 'locationType', 'quarter'],
      id: 'modesoftransport',
      name: 'Modes of Transport',
      type: 'pie',
    },
  ],

  [Slide.AVIATION_INBOUND]: [
    {
      url: 'InboundAviation/charts/topairlines',
      params: ['quarter'],
      id: 'topairlines',
      name: 'Top Airlines',
      type: 'bar',
    },
    {
      url: 'InboundAviation/charts/topcountries',
      params: ['quarter'],
      id: 'topcountries',
      name: 'Top Countries',
      type: 'bar',
    },
  ],

  [Slide.AVIATION_OUTBOUND]: [
    {
      url: 'outboundAviation/charts/topairlines',
      params: ['quarter'],
      id: 'topairlines',
      name: 'Top Airlines',
      type: 'bar',
    },
    {
      url: 'outboundAviation/charts/topcountries',
      params: ['quarter'],
      id: 'topcountries',
      name: 'Top Countries',
      type: 'bar',
    },
  ],

  [Slide.AVIATION_CONNECTIVITY]: [
    {
      url: 'connectivityAviation/charts/breakdown',
      params: ['quarter'],
      id: 'breakdown',
      name: '7 Days Connectivity',
      type: 'pie',
    },
  ],

  [Slide.MARITIME_FACILITIES]: [
    {
      url: 'MaritimeFacilities/charts/slipwayBreakdown',
      params: ['quarter'],
      id: 'slipwayBreakdown',
      name: 'Slipway Breakdown',
      type: 'bar',
    },
  ],

  [Slide.MARITIME_TRIPS]: [
    {
      url: 'MaritimeTrips/charts/tripsBreakdown',
      params: ['quarter'],
      id: 'tripsBreakdown',
      name: 'Trips Breakdown',
      type: 'pie',
    },
  ],

  [Slide.TRAFFIC_OVERVIEW]: [
    {
      url: 'RoadTraffic/charts/mostcongestedstreets',
      params: ['location', 'locationType', 'quarter'],
      id: 'mostcongestedstreets',
      name: 'Most Congested Streets',
      type: 'list',
      keyLabel: 'Street Name',
    },
    {
      url: 'accidents/charts/injurytypes',
      params: ['location', 'locationType', 'quarter'],
      id: 'injurytypes',
      name: 'Injury Types',
      type: 'pie',
    },
  ],

  [Slide.ROAD_TRAFFIC]: [
    {
      url: 'RoadTraffic/charts/mostcongestedstreets',
      params: ['location', 'locationType', 'quarter'],
      id: 'mostcongestedstreets',
      name: 'Most Congested Streets',
      type: 'list',
      keyLabel: 'Street Name',
    },
    {
      url: 'RoadTraffic/charts/mostusedentrypoints',
      params: ['location', 'locationType'],
      id: 'mostusedentrypoints',
      name: 'Most Used Entry Points',
      unavailableLocation: [LocationType.EMIRATE],
      type: 'bar',
    },
    {
      url: 'RoadTraffic/charts/mostusedexitpoints',
      params: ['location', 'locationType'],
      id: 'mostusedexitpoints',
      name: 'Most Used Exit Points',
      unavailableLocation: [LocationType.EMIRATE],
      type: 'bar',
    },
  ],

  [Slide.JUNCTIONS]: [
    {
      url: 'junctionlevelofservice/charts/shareoffailing',
      params: ['location', 'locationType', 'allMonthsOfPeriod'],
      id: 'shareoffailingjunctions',
      name: 'Share of Failing Junctions',
      type: 'ring',
    },
    {
      url: 'junctionlevelofservice/charts/levelofservice',
      params: ['location', 'locationType', 'allMonthsOfPeriod'],
      id: 'levelofservice',
      name: 'Level of Service',
      type: 'pie',
    },
    {
      url: 'junctionlevelofservice/charts/topcongested',
      params: ['location', 'locationType', 'allMonthsOfPeriod'],
      id: 'topcongestedjunctions',
      name: 'Top Congested Junctions',
      type: 'table',
      keyLabel: 'Junction',
      valueLabel: '',
    },
  ],

  [Slide.ACCIDENTS]: [
    {
      url: 'accidents/charts/accidenttypes',
      params: ['location', 'locationType', 'quarter'],
      id: 'accidenttypes',
      name: 'Accident Types',
      type: 'pie',
    },
    {
      url: 'accidents/charts/injurytypes',
      params: ['location', 'locationType', 'quarter'],
      id: 'injurytypes',
      name: 'Injury Types',
      type: 'pie',
    },
    {
      url: 'accidents/charts/topvehicletypes',
      params: ['location', 'locationType', 'quarter'],
      id: 'topvehicletypes',
      name: 'Top Vehicle Types',
      type: 'table',
      keyLabel: 'Type',
      valueLabel: 'Accidents',
    },
    {
      url: 'accidents/charts/topnationalities',
      params: ['location', 'locationType', 'quarter'],
      id: 'topnationalities',
      name: 'Top Nationalities',
      type: 'table',
      keyLabel: 'Country',
      valueLabel: 'Accidents',
    },
    {
      url: 'accidents/charts/accidentsnumber',
      params: ['location', 'locationType', 'quarter'],
      id: 'accidentsnumber',
      name: 'Number of Accidents / km²',
      type: 'persquare',
      label: 'Accidents/km²',
    },
  ],
};
